### ISSUE TITLE
Cannot find plugin "karma-systemjs"

### ISSUE THREAD

**Issue by kosz** [rolaveric/karma-systemjs#49]
I'm getting this error: 

```
06 10 2015 21:37:21.906:WARN [plugin]: Cannot find plugin "karma-systemjs".
  Did you forget to install it ?
  npm install karma-systemjs --save-dev
/Users/cosmin/.nvm/v0.12.4/lib/node_modules/karma/node_modules/di/lib/injector.js:9
      throw error('No provider for "' + name + '"!');
            ^
Error: No provider for "framework:systemjs"! (Resolving: framework:systemjs)
    at error (/Users/cosmin/.nvm/v0.12.4/lib/node_modules/karma/node_modules/di/lib/injector.js:22:68)
    at Object.parent.get (/Users/cosmin/.nvm/v0.12.4/lib/node_modules/karma/node_modules/di/lib/injector.js:9:13)
    at get (/Users/cosmin/.nvm/v0.12.4/lib/node_modules/karma/node_modules/di/lib/injector.js:54:19)
    at /Users/cosmin/.nvm/v0.12.4/lib/node_modules/karma/lib/server.js:137:20
```

"No I did not forget to install it" 

I have this in package.json: 

```
...
"devDependencies: {
   ...
   "karma-systemjs": "^0.8.0",
   ...
}
...
```

I have this in my karma.conf.js

``` 
plugins: ['karma-systemjs'],
frameworks: ['systemjs', 'mocha'],
```

and inside my proj_dir/node_modules/karma-systemjs/package.json I see this: 

```
...
"name": "karma-systemjs",
"version": "0.8.0",
...
```

other details: 
```
✔ ~
21:44 $ karma --version
Karma version: 0.13.10
✔ ~
21:44 $ node --version
v0.12.4
✔ ~
21:44 $ npm --version
2.10.1
✔ ~
21:44 $ uname -v
Darwin Kernel Version 14.5.0: Wed Jul 29 02:26:53 PDT 2015; root:xnu-2782.40.9~1/RELEASE_X86_64
( OSX 10.10.5 )
```

**Comment by rolaveric** [comment]
Going by the paths in your error (`/Users/cosmin/.nvm/v0.12.4/lib/node_modules/karma`) I'd guess that Karma is looking for plugins that have been installed globally, rather than locally.

**Comment by kosz** [comment]
yea that makes sense, looks like I need to use the locally installed executable ...
`./node_modules/karma/bin/karma start` works

pretty weird behaviour from karma, I'd assume the global CLI is expected to be used, it should be able to find locally installed plugins >:

anyways, thanks for your help and quick response

**Comment by vb8190** [comment]
I am facing the same issue. It seems karma is looking for plugins locally but I am still getting this issue.

C:\osd\forms\node_modules\karma\node_modules\di\lib\injector.js:9
      throw error('No provider for "' + name + '"!');
            ^
Error: No provider for "framework:systemjs"! (Resolving: framework:systemjs)
  at error (C:\osd\forms\node_modules\karma\node_modules\di\lib\injector.js:22:68)
  at Object.parent.get (C:\osd\forms\node_modules\karma\node_modules\di\lib\injector.js:9:13)
  at [object Object].get (C:\osd\forms\node_modules\karma\node_modules\di\lib\injector.js:54:19)
  at C:\osd\forms\node_modules\karma\lib\server.js:133:20
  at Array.forEach (native)
  at [object Object].Server._start (C:\osd\forms\node_modules\karma\lib\server.js:132:21)
  at [object Object].invoke (C:\osd\forms\node_modules\karma\node_modules\di\lib\injector.js:75:15)
  at [object Object].Server.start (C:\osd\forms\node_modules\karma\lib\server.js:97:18)
  at Object.exports.run (C:\osd\forms\node_modules\karma\lib\cli.js:231:26)
  at Object.<anonymous> (C:\osd\forms\node_modules\karma\bin\karma:3:23)
  at Module._compile (module.js:460:26)
  at Object.Module._extensions..js (module.js:478:10)
  at Module.load (module.js:355:32)
  at Function.Module._load (module.js:310:12)
  at Function.Module.runMain (module.js:501:10)
  at startup (node.js:129:16)
  at node.js:814:3
